### ISSUE TITLE
how to start contributing via CMoC

### ISSUE THREAD

**Issue by Parikshit-Hooda** [himanshukumar660/Vessel-Tracking#1]
i am interested in this project but there are no instructions to getting started with contributing.

**Comment by himanshukumar660** [comment]
Hey,

I would soon be updatig the Readme with relevent details to get started.

Regards,

**Comment by himanshukumar660** [comment]
i have updated the README.md. You could go through it.

**Comment by Parikshit-Hooda** [comment]
okay. thanks.
